src/Entity/Task.php
<?php

namespace App\Entity;

use App\Repository\TaskRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TaskRepository::class)
 */
class Task
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $comment;

    /**
     * @ORM\Column(type="date")
     */
    private $date;

    /**
     * @ORM\Column(type="integer")
     */
    private $time_spent;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="tasks")
     */
    private $UserTask;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getTimeSpent(): ?int
    {
        return $this->time_spent;
    }

    public function setTimeSpent(int $time_spent): self
    {
        $this->time_spent = $time_spent;

        return $this;
    }

    public function getUserTask(): ?User
    {
        return $this->UserTask;
    }

    public function setUserTask(?User $UserTask): self
    {
        $this->UserTask = $UserTask;

        return $this;
    }

    public function toArray()
    {
        return array(
            $this->title,
            $this->comment,
            $this->date->format('Y-m-d'),
            $this->time_spent,
        );
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" href="{{ asset('css/styles.css') }}">
        {% block stylesheets %}{% endblock %}

        {% block javascripts %}{% endblock %}
    </head>
    <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                {% if app.user %}
                    <li class="nav-item active">
                        <a class="nav-link" href="{{ path('tasks') }}">Profile</a>
                    </li>

                <li class="nav-item">
                    <a class="nav-link" href="{{ path('app_logout') }}">Logout</a>
                </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ path('register') }}">Regiser</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{{ path('app_login') }}">Login</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>

        {% block body %}{% endblock %}
    </body>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</html>

templates/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <div class="my-bg-full">
        <div class="container">
            <h2>Register panel</h2>

            {{ form(form) }}

        </div>
    </div>

{% endblock %}

templates/tasks.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <div class="my-bg">
        <div class="container">
            <h2>Available options</h2>

            <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#add-task" aria-expanded="false" aria-controls="add-task">
                Add new task
            </button>

            <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#generate-report" aria-expanded="false" aria-controls="generate-report">
                Generate report
            </button>

            <div class="row mt-5">

                <div class="collapse mx-auto show" id="add-task">
                    <div class="card card-body">
                        {{ form(formTask) }}
                    </div>
                </div>

                <div class="collapse mx-auto" id="generate-report">
                    <div class="card card-body">
                        {{ form(formReport) }}
                    </div>
                </div>

            </div>

        </div>
    </div>

    <ul id="tasks">
        {% for task in tasks %}
            <li>
                <span class="task-list-item">{{ task.title }} {% if task.comment %}(comment: {{ task.comment }}){% endif %} <b>added on {{ task.date.date | date("m/d/Y") }}</b></span><span class="date">the duration of {{ task.timeSpent }} mins</span>
            </li>
        {% endfor %}
    </ul>

    {{ knp_pagination_render(tasks) }}

{% endblock %}